# Generated by Django 4.0.5 on 2022-06-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('fileId', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('fileName', models.TextField(null=True)),
                ('filePath', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='audiofiles/')),
                ('error', models.CharField(max_length=100, null=True)),
                ('probability', models.FloatField()),
                ('phishingType', models.CharField(max_length=50, null=True)),
                ('isAllowed', models.BooleanField(default=False)),
            ],
        ),
    ]
